In [2]:
import torch

In [3]:
x = torch.arange(12, dtype = torch.float32)

In [4]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3, 4)

In [7]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.arange(15, dtype = torch.float32).reshape(3,5)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [15]:
torch.zeros(2,2,3,4)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [17]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
torch.randn(3, 6)

tensor([[ 0.6450,  1.0203,  0.3511,  0.7971,  1.2418,  0.9212],
        [ 0.8047, -0.1854, -0.8071, -0.6790, -0.9977, -0.9007],
        [ 0.2007,  0.5814,  1.2885, -0.1794,  0.8612,  2.1063]])

In [19]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [20]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
X[1][1]

tensor(5.)

In [22]:
X[-1][1:]

tensor([ 9., 10., 11.])

In [24]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
X[1][2] = 17

In [26]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
X[1,2] = 21
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 21.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
X[:2, :1]

tensor([[0.],
        [4.]])

In [29]:
X[:3, :1] = 11

In [30]:
X

tensor([[11.,  1.,  2.,  3.],
        [11.,  5., 21.,  7.],
        [11.,  9., 10., 11.]])

In [31]:
x = torch.tensor([1., 2, 4, 8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, y / x, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([2.0000, 1.0000, 0.5000, 0.2500]),
 tensor([ 1.,  4., 16., 64.]))

In [32]:
torch.cat((x, y))

tensor([1., 2., 4., 8., 2., 2., 2., 2.])

In [34]:
torch.cat((x, y), dim = 0)

tensor([1., 2., 4., 8., 2., 2., 2., 2.])

In [35]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [36]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [37]:
X.sum()

tensor(66.)